# MPI C++ compiler
CXX 		= mpicxx
CC		= $(CXX)

# Passed to compiler
OPT_LEVEL	= -O2
DEBUG_LEVEL	= -g
EXTRA_CCFLAGS	= -Wall
CXXFLAGS	= $(OPT_LEVEL) $(DEBUG_LEVEL) $(EXTRA_CCFLAGS) -fPIC
CCFLAGS		= $(CXXFLAGS)

# Passed to the C pre-processor
CPPFLAGS        = -I./ 

# Passed to the linker
LDFLAGS         = -L./ 

# Link with these libraries
LDLIBS          =

# Installation path
prefix		= ./lib
