
# MPI C++ compiler
CXX 		= mpiicc  -fPIC
CC		= $(CXX)

# Passed to compiler
OPT_LEVEL	= -O2
DEBUG_LEVEL	= -g -std=c++0x -pthread 
#DEBUG_LEVEL	= -g -pthread 
EXTRA_CCFLAGS	= -Wall
CXXFLAGS	= $(OPT_LEVEL) $(DEBUG_LEVEL) $(EXTRA_CCFLAGS) 
CCFLAGS		= $(CXXFLAGS) 

# Passed to the C pre-processor
CPPFLAGS        = -I./ -I../src
CFLAGS		= $(CPPFLAGS)

# Passed to the linker
LDFLAGS         = -L./ -lstdc++ 

# Link with these libraries
LDLIBS          =

# Installation path
prefix		= ./lib

