
PREFIX=/g/g90/sato5/repo/rempi/

# MPI C++ compiler
CXX 		= mpicc
CC		= $(CXX)
FC		= mpif90

# Passed to compiler
OPT_LEVEL	= -O2
DEBUG_LEVEL	= -g 
EXTRA_CCFLAGS	= -fPIC -Wall
INCLUDES        = -I./ -I../src -I${PREFIX}/src/external/clmpi -pthread 
CXXFLAGS	= $(OPT_LEVEL) $(DEBUG_LEVEL) $(EXTRA_CCFLAGS) -std=c++0x
CFLAGS		= $(OPT_LEVEL) $(DEBUG_LEVEL) $(EXTRA_CCFLAGS)

# Passed to the C pre-processor
#CPPFLAGS        = -DREMPI_LITE
CPPFLAGS        = 

# Passed to the linker
#LDFLAGS         = -L./ -lstdc++  -L/g/g90/sato5/opt/lib -lpnmpi -lz -lintlc
LDFLAGS          = -L./

# Link with these libraries
LDLIBS          =  -lstdc++ -lz #-lintlc

# Installation path
prefix		= ./lib

